repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use a specific, recent revision
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.0 # Use a specific, recent revision
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0 # Use a specific, recent revision
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Use a specific, recent revision
    hooks:
      - id: isort
        args: ["--profile", "black"] # Integrate with Black's formatting style
